name: nonce-service build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: docker build -t nonce-service .
      - name: docker tag
        run: |
          docker tag nonce-service feinwaru/nonce-service:${{ github.sha }}
          docker tag nonce-service feinwaru/nonce-service:latest
      - name: docker push
        run: |
          docker push feinwaru/nonce-service:${{ github.sha }}
          docker push feinwaru/nonce-service:latest
