name: nonce-service cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: save kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show bandsy-main > $GITHUB_WORKSPACE/.kubeconfig
      - name: install helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
      - name: helm install
        run: helm install nonce-service $GITHUB_WORKSPACE/chart
