name: nonce-service ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v1
      - name: install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - name: test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
  build:
    name: build
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: docker build -t nonce-service .
      - name: docker tag
        run: |
          docker tag nonce-service feinwaru/nonce-service:${{ github.sha }}
          docker tag nonce-service feinwaru/nonce-service:latest
      - name: docker push
        run: |
          docker push feinwaru/nonce-service:${{ github.sha }}
          docker push feinwaru/nonce-service:latest
  cd:
    name: cd
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: save kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-bandsy > $GITHUB_WORKSPACE/.kubeconfig
      - name: install helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
      - name: helm init
        run: helm init --client-only --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig
      - name: helm install
        run: helm install nonce-service ./chart
